<a href="https://colab.research.google.com/github/Hermina-dev/Jeu-de-la-vie/blob/main/Evans_%26_Hermine_(jeu_de_la_vie).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#le jeu de la vie

import random
import numpy as np
import time as time

#I - DEFINITION DES PARAMETRES

#1-Taille de la grille
Grille = np.zeros((7, 7))

#2-Etat des cellules
cellule_vivante = 1
cellule_morte = 0

#3-afficher la grille avec les cellules vivantes et mortes
for x in range(Grille.shape[0]):
    for y in range(Grille.shape[1]):
        Grille[x, y] = random.choice([cellule_vivante, cellule_morte])

print(" la grille est la suivante :")
print (Grille)

#ZERO PADDING
Grille[0, :] = cellule_morte
Grille[-1, :] = cellule_morte
Grille[:, 0] = cellule_morte
Grille[:, -1] = cellule_morte

print(" la nouvelle  grille est la suivante :")
print (Grille)

#II-GENERATION DES NOUVELLES GRILLES

#1_ Fonction pour compter les voisins vivants
def compter_voisins(grille, i, j):
    voisins = np.sum(grille[i-1:i+2, j-1:j+2]) - grille[i, j]
    return voisins

#2_ Fonction pour générer la génération suivante
def nouvelle_generation(grille_actuelle):
    nouvelle_grille = np.copy(grille_actuelle)
    lignes, colonnes = grille_actuelle.shape

    for i in range(1, lignes - 1):
        for j in range(1, colonnes - 1):
            nb_voisins = compter_voisins(grille_actuelle, i, j)

            if grille_actuelle[i, j] == cellule_vivante:
                if nb_voisins < 2 or nb_voisins > 3:
                    nouvelle_grille[i, j] = cellule_morte
                else:
                    nouvelle_grille[i, j] = cellule_vivante
            else:
                if nb_voisins == 3:
                    nouvelle_grille[i, j] = cellule_vivante

    nouvelle_grille[0, :] = cellule_morte
    nouvelle_grille[-1, :] = cellule_morte
    nouvelle_grille[:, 0] = cellule_morte
    nouvelle_grille[:, -1] = cellule_morte

    return nouvelle_grille

# III - SIMULATION
nb_generations = 10

for generation in range(nb_generations):
    print(f"\n--- Génération {generation + 1} ---")
    Grille = nouvelle_generation(Grille)
    print(Grille)
    time.sleep(0.5)

print("stop")





 la grille est la suivante :
[[1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0.]]
 la nouvelle  grille est la suivante :
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

--- Génération 1 ---
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

--- Génération 2 ---
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

--- Génération 3 ---
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

--- Génération 4 ---